### ISSUE TITLE
Opencv can't move thread to another one 

### ISSUE THREAD

**Issue by kiloa44** [skvark/opencv-python#215] opened 2019-06-23 14:03 UTC
The library has a problem in dealing with Qt objects when it tries to move from a thread to another, which causes a crash with an exit code (139).
here is the code which fails at `cv2.imshow('frame',gray)`:

`import numpy as np`
`import cv2`
`cap = cv2.VideoCapture(0)`
`while(True):`
`    # Capture frame-by-frame`
`    ret, frame = cap.read()`
`    # Our operations on the frame come here`
`    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)`
`    # Display the resulting frame`
`    cv2.imshow('frame',gray)`
`    if cv2.waitKey(1) & 0xFF == ord('q'):`
`        break`
`# When everything done, release the capture`
`cap.release()`
`cv2.destroyAllWindows()`

and this is the output of the code:

> QObject::moveToThread: Current thread (0x19a67b0) is not the object's thread (0x1a497b0).
Cannot move to target thread (0x19a67b0)

**Comment by skvark** [comment] 2019-06-23 15:20
Duplicate of https://github.com/skvark/opencv-python/issues/46. This will not be fixed because the error is caused by conflicting Qt installations.

**Closed by skvark** 2019-06-23 15:20 UTC
