### ISSUE TITLE
OpenCV 4.2.0 has been released

### ISSUE THREAD

**Issue by johnthagen** [skvark/opencv-python#280] opened 2020-01-04 14:49 UTC
[OpenCV 4.2.0](https://github.com/opencv/opencv/wiki/ChangeLog#version420) was released on December 20, 2019. Could an `opencv-python` build of this be released?

Thanks.

**Comment by adamhrv** [comment] 2020-01-06 14:41
Temporary solution to build 4.2.0 that also enables the new DNN CUDA options https://github.com/opencv/opencv/pull/14827#issuecomment-571102168

**Comment by skvark** [comment] 2020-01-06 16:06
I'll make the release during this week.

**Comment by skvark** [comment] 2020-01-13 10:03
There are issues with macOS builds (3.4 builds are failing, but master should have the same issue). Related to OpenSSL version deprecation. Qt4 might need an upgrade to Qt5 to get the builds passing.

**Comment by skvark** [comment] 2020-01-23 06:34
This is taking longer than expected. I'm too busy with work and other stuff currently but I'll try have a look as soon as possible. 3.4 branch contains some modifications / commits which I have tried already if someone would like to have a look.

**Comment by Borda** [comment] 2020-02-01 08:56
@skvark you are talking about 3.4 but this issue is about 4.2
So is there a chnace to have it on pip too?

**Comment by skvark** [comment] 2020-02-01 10:49
Yes, of course. The issue is not related to OpenCV version as explained above (Qt / OpenSSL upgrade causes issues).

**Comment by skvark** [comment] 2020-02-01 12:30
Seems like the macOS problem is solved now. ``multibuild`` had also a bug which has been now fixed. If everything looks ok after these changes I can finally make the releases.

**Comment by skvark** [comment] 2020-02-02 18:59
4.2.0 builds are now in progress. 3.4.9 is already in PyPI.

**Comment by johnthagen** [comment] 2020-02-02 20:21
https://pypi.org/project/opencv-python/4.2.0.32/

:tada:!

**Comment by skvark** [comment] 2020-02-02 20:34
Please note that it takes many hours before all the wheels have been built and uploaded. I'm closing this issue now, please open a new one if you encounter any issues.

**Closed by skvark** 2020-02-02 20:34 UTC
