### ISSUE TITLE
Video capture - failed recording my screen on mac os, output is corrupted 

### ISSUE THREAD

**Issue by bwomsm1** [skvark/opencv-python#805] opened 2023-02-23 09:45 UTC
### Expected behaviour

I am trying to record my screen with the example code below, but when I am trying to play the output I get this: 
<img width="267" alt="Screenshot 2023-02-23 at 11 45 09" src="https://user-images.githubusercontent.com/5571230/220872093-d47262ed-3677-4a0b-94c4-ae931f62d425.png">

### Actual behaviour

**The code does working correctly on Windows OS**

### Steps to reproduce

- example code
```
# Importing the necessary libraries
import pyautogui
import numpy
import cv2
import time
from os import system

# Obtaining the screen height and width
screenWidth, screenHeight = pyautogui.size()
print((screenWidth, screenHeight))

system('rm -rf screen_test.mp4')
result = cv2.VideoWriter(
    'screen_test.mp4',
    cv2.VideoWriter_fourcc(*'mp4v'),
    10.0,
    (screenWidth, screenHeight)
)

# Setting the starting timer for the required duration
end_time = time.time() + 7

while True:
    # Record the screenshots of each image to create a video
    images = pyautogui.screenshot()
    frames = numpy.array(images)
    frames_RGB = cv2.cvtColor(frames, cv2.COLOR_BGR2RGB)

    # Saving the result
    result.write(frames_RGB)

    # Breaking the loop after the specific time has exceeded
    if time.time() >= end_time:
        break

result.release()
print("OUTPUT SAVED...")
```

- operating system
Mac OS ventura 13.2.1 (22D68)
- architecture (e.g. x86)
- opencv-python version
4.7.0.68

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by VadimLevin** [comment] 2023-02-27 07:46
macOS 12.6.3
Python 3.10.9
OpenCV version: 4.7.0.68

Everything works as expected.
Have you granted permissions to record screen in "Security & Privacy"?
Have you experienced same issue with different codecs? e.g. motion jpeg:
```python
result = cv2.VideoWriter(
    'screen_test.avi',
    cv2.VideoWriter_fourcc(*'MJPG'),
    10.0,
    (screenWidth, screenHeight)
)
```
@bwomsm1  Can you provide `ffprobe screen_test.mp4` output? e.g. output on my machine
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'screen_test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:03.10, start: 0.000000, bitrate: 4142 kb/s
  Stream #0:0[0x1](und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 4139 kb/s, 10 fps, 10 tbr, 10240 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

**Comment by bwomsm1** [comment] 2023-02-27 08:26
@VadimLevin I uploaded the `mp4` file to https://github.com/bwomsm1/AppiumLogs/blob/master/with_mp4v_encoding.mp4

<br>
Not sure I can play `avi` files on mac, correct? 

<br>
(I did grant permissions to record screen in "Security & Privacy") 


<br>

```
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/5.1.2_4 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'with_mp4v_encoding.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:00.00, bitrate: N/A
```



Name: opencv-python
Version: 4.7.0.68

**Comment by VadimLevin** [comment] 2023-02-27 09:35
You can play '.avi' files on any system having necessary codecs.
It looks like created file doesn't contain any video stream... which is weird...
Is assertion passing?
```python
assert result.isOpened()
```
Try to use different container (e.g. 'avi') with different codecs (e.g. 'H264'/'MJPG'/'X264'/'XVID')

**Comment by bwomsm1** [comment] 2023-02-27 09:53
> ```python
> isOpened
> ```

For this code: 
```
print(result.isOpened())
result.release()
print(result.isOpened())
print("OUTPUT SAVED...")
```

I got this output:
```
True
False
OUTPUT SAVED...
```
@VadimLevin

**Comment by bwomsm1** [comment] 2023-02-27 09:59
I tried to record with all this coded: 'H264'/'MJPG'/'X264'/'XVID',
<br>

Recorded on mac and tried to play them both in Mac or Win, but failed in both platforms to play. 
<br>
File extention was `avi`

**Comment by bwomsm1** [comment] 2023-02-28 11:23
@VadimLevin any chance you know something about this issue?

**Comment by VadimLevin** [comment] 2023-02-28 11:56
It sounds weird, I wander that the issue hides somewhere in backend codecs.

You can try to switch between different backends explicitly specifying `apiPreference` argument.
As far as you have `ffprobe` you can use FFMPEG backend:
```python
result = cv2.VideoWriter(
    'screen_test.mp4',
    cv2.CAP_FFMPEG,
    cv2.VideoWriter_fourcc(*'mp4v'),
    10.0,
    (screenWidth, screenHeight)
)
```
if you have installed gstreamer on your macOS machine, you can specify `cv2.CAP_GSTREAMER` as `apiPreference` or even provide gstreamer pipeline as an argument. Example:
```python
writer = cv2.VideoWriter(
    'appsrc ! videoconvert ! x264enc ! filesink location=screen_test.mp4',
    0, 10.0,
    (screenWidth, screenHeight)
)
```

**Comment by bwomsm1** [comment] 2023-02-28 13:17
Sorry @VadimLevin but nothing really helped, I tired both suggestion above. 
<br>
Any chance we can have zoom call?

**Comment by skvark** [comment] 2023-02-28 15:16
```
images = pyautogui.screenshot()
frames = numpy.array(images)
frames_RGB = cv2.cvtColor(frames, cv2.COLOR_BGR2RGB)
```

The screenshot function might return a different type of image on Windows than on macOS. Could you confirm that the frames_RGB contains a valid image on macOS?

**Comment by bwomsm1** [comment] 2023-02-28 17:40
@skvark I can confirm that by running the following 3 lines:
```
images = pyautogui.screenshot()
frames = numpy.array(images)
frames_RGB = cv2.cvtColor(frames, cv2.COLOR_BGR2RGB)
```
Some png file named `screenshot2023-0227_11-55-29-781627` was created but I was not able to open it on mac

**Comment by bwomsm1** [comment] 2023-02-28 17:46
@skvark , sending again my script:
```
# Importing the necessary libraries
import pyautogui
import numpy
import cv2
import time
from os import system

print('script starts ...')
# Obtaining the screen height and width
screenWidth, screenHeight = pyautogui.size()

extention = 'mp4'
codeded = 'mp4v'
system('rm -rf screen_test.%s' % extention)
result = cv2.VideoWriter(
    'test.%s' % extention,
    cv2.VideoWriter_fourcc(*codeded),
    10.0,
    (screenWidth, screenHeight)
)

# Setting the starting timer for the required duration
end_time = time.time() + 4

while True:
    images = pyautogui.screenshot()
    frames = numpy.array(images)
    frames_RGB = cv2.cvtColor(frames, cv2.COLOR_BGR2RGB)

    # Saving the result
    result.write(frames_RGB)

    # Breaking the loop after the specific time has exceeded
    if time.time() >= end_time:
        break

result.release()
print("OUTPUT SAVED...")
```

Can you check if it is working on your local Mac?

**Comment by skvark** [comment] 2023-02-28 17:57
I don't own a Mac, sorry. But it looks like the issue is in `pyautogui.screenshot()`. Pyautogui depends on https://github.com/asweigart/pyscreeze, and it was updated last time in 2021. macOS Ventura was released in 2022, so it might be incompatible with the newest macOS version. But I'm just guessing here because it works on macOS 12.6.3, as tested by @VadimLevin.

**Comment by bwomsm1** [comment] 2023-02-28 18:12
@skvark you are awesome, great conclusion, 
I just tested the script above with `Mac OS 12.6.3` and it seems that my script is working and a video was recorded. 

But what next? Where I should push in order to have it working on mac OS `13.*`

Please instruct me, does the following **issue** title for https://github.com/asweigart/pyscreeze/issues:
**"pyautogui.screenshot() method is not working on `Mac OS 13.2.1`"** hit the point?

**Comment by skvark** [comment] 2023-03-01 05:40
You can probably work around the issue by using https://pillow.readthedocs.io/en/latest/reference/ImageGrab.html instead of pyautogui. It looks like the pyscreeze package is not maintained actively.

**Comment by bwomsm1** [comment] 2023-03-01 06:25
Thanks @skvark ,
the `numpy.array` expected for one of the following image types `'ndarray | Iterable | int | float'`,
Do you know how I can get from `img`:
`img = ImageGrab.grab(bbox=None)`

The type it expects to?

**Comment by skvark** [comment] 2023-03-01 08:04
I think `numpy.array(img)` should do the trick. Check if `img = ImageGrab.grab(bbox=None)` returned an actual image by saving it to disk with PIL. If not, there's probably some permission issue, or the screen capture doesn't work for some reason. But I'm not a macOS expert, and this is not really in the scope of this repository since this issue seems to be related to your operating system behavior.

**Comment by bwomsm1** [comment] 2023-03-01 08:33
@skvark it did return the `image` object, have no idea what is the problem...

**Comment by asmorkalov** [comment] 2023-03-15 07:02
The issue is not related to OpenCV, but other package. Closed.

**Closed as completed by asmorkalov** 2023-03-15 07:02 UTC
Labels: question
