### ISSUE TITLE
Missing type hints for OpenCV data types

### ISSUE THREAD

**Issue by robertschweizer** [skvark/opencv-python#895] opened 2023-08-25 17:12 UTC
### Expected behaviour

Mypy should pass when using valid `cv2` members.

### Actual behaviour

Mypy fails when accessing OpenCV data types, e.g. `cv2.CV_32S`:

```
test.py:2: error: Module has no attribute "CV_32S"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

### Steps to reproduce

Run mypy 1.5.1 and `opencv-python-headless==4.8.0.76` on 

```py
import cv2
print(cv2.CV_32S)
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by VadimLevin** [comment] 2023-08-28 07:38
The issue is resolved in opencv/opencv#23954.
Patch will be a part of next release.

**Closed as completed by VadimLevin** 2023-08-28 07:38 UTC
