### ISSUE TITLE
About yolov4?

### ISSUE THREAD

**Issue by IDGate-ai** [skvark/opencv-python#327] opened 2020-05-18 10:21 UTC
### Expected behaviour

Recently, yolov4 release. However, dnn.readNetFromDarknet do not work for yolov4. Fortunately, [issue have been solved](https://github.com/opencv/opencv/pull/17185). However, this has not been updated in opencv-contrib-python package. Will this update recently?

### Actual behaviour

cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yolov4_test.py", line 6, in <module>
    net = cv.dnn_DetectionModel(modelConfiguration, modelWeights)
SystemError: <class 'cv2.dnn_DetectionModel'> returned a result with an error set

### Steps to reproduce

- example code

import cv2 as cv

modelConfiguration = "yolo-obj.cfg"
modelWeights = "yolo-obj_9000.weights"

net = cv.dnn_DetectionModel(modelConfiguration, modelWeights)
net.setInputSize(608)
net.setInputScale(1.0 / 255)
net.setInputSwapRB(True)

frame = cv.imread('7755dd9f7f9de57b.jpg')

with open('obj.names', 'rt') as f:
    names = f.read().rstrip('\n').split('\n')

classes, confidences, boxes = net.detect(frame, confThreshold=0.1, nmsThreshold=0.4)
for classId, confidence, box in zip(classes.flatten(), confidences.flatten(), boxes):
    label = '%.2f' % confidence
    label = '%s: %s' % (names[classId], label)
    labelSize, baseLine = cv.getTextSize(label, cv.FONT_HERSHEY_SIMPLEX, 0.5, 1)
    left, top, width, height = box
    top = max(top, labelSize[1])
    cv.rectangle(frame, box, color=(0, 255, 0), thickness=3)
    cv.rectangle(frame, (left, top - labelSize[1]), (left + labelSize[0], top + baseLine), (255, 255, 255), cv.FILLED)
    cv.putText(frame, label, (left, top), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0))

cv.imshow('out', frame)

- operating system
Ubuntu 18.04
- architecture 
x64
- opencv-python version
4.2.0.34

**Comment by mshabunin** [comment] 2020-05-21 17:16
It's not working yet, wait for the next OpenCV release.

**Comment by sky-fly97** [comment] 2020-06-27 14:41
Hello, I want to know that I can't call yolov4's model with DNN yet？

**Comment by mon28** [comment] 2020-07-06 05:57
The next opencv release is here today! Yet I don't see this issue solved. Can anyone confirm? I am working with 4.3.0.36

**Comment by skvark** [comment] 2020-07-06 06:21
The issue is not really related to this repository. To my knowledge, Yolov4 support will be in the upcoming 3.4.11 and 4.4.0 releases. Please follow OpenCV's issue tracker and changelogs.

https://github.com/opencv/opencv/issues/17479

**Closed by skvark** 2020-07-06 06:21 UTC

**Comment by pkkota-dev** [comment] 2020-08-10 16:56
Am also facing this issue am not able to figure out the resolution can any one suggest do i need to install any specific version of opencv currently installed version in my machine is 4.3.0

**Comment by skvark** [comment] 2020-08-10 17:12
> 
> 
> The issue is not really related to this repository. To my knowledge, Yolov4 support will be in the upcoming 3.4.11 and 4.4.0 releases. Please follow OpenCV's issue tracker and changelogs.
> 
> [opencv/opencv#17479](https://github.com/opencv/opencv/issues/17479)

Quoting myself: wait for 3.4.11 and 4.4.0.
