### ISSUE TITLE
Could not load the Qt platform plugin

### ISSUE THREAD

**Issue by sadams207** [skvark/opencv-python#427] opened 2020-12-09 13:50 UTC
### Expected behaviour

Application with matplotlib should be able to show a plot window. 

### Actual behaviour

Segmentation fault during the plotting process. 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/sadams/projects/meccanoFork/venv/lib/python3.8/site-packages/**cv2/qt/plugins**" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

### Steps to reproduce

- example code
`import cv2
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

print(f'Build information: {cv2.getBuildInformation()}')
print(f'CV2 Version: {cv2.__version__}')
print(f'Matplotlib Version: {matplotlib.__version__}')
x = np.linspace(0,1,10)
plt.figure()
plt.plot(x)
plt.show()
`

See attached for build information.
Version control:               4.4.0-dirty
[qt_debug.txt](https://github.com/skvark/opencv-python/files/5666251/qt_debug.txt)

##### Issue submission checklist

 - [ X] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ X] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ IDK] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ X] I'm using the latest version of ``opencv-python``

**Comment by sadams207** [comment] 2020-12-09 13:52
I realize that this is similar to IMShow No Window - 4.4.0.46 MacOS Big Sur #423; 
however, this shows that it is not just Mac related.

**Comment by skvark** [comment] 2020-12-09 14:04
Duplicate of https://github.com/skvark/opencv-python/issues/386 and https://github.com/skvark/opencv-python/issues/404.

**Closed by skvark** 2020-12-09 14:04 UTC
