### ISSUE TITLE
OpenCV 4.3.0 has been released

### ISSUE THREAD

**Issue by johnthagen** [skvark/opencv-python#331] opened 2020-05-21 01:08 UTC
[OpenCV 4.3.0](https://github.com/opencv/opencv/wiki/ChangeLog#version430) was released on April 2020. Could an `opencv-python` build of this be released?

Thanks.

**Comment by johnthagen** [comment] 2020-05-21 01:09
Looks like this might have already been started: 35755449c6f233d877fac7594e5af82f8642fcac

**Comment by skvark** [comment] 2020-05-21 08:33
Duplicate of https://github.com/skvark/opencv-python/issues/316

**Closed by skvark** 2020-05-21 08:33 UTC
