### ISSUE TITLE
Where is cv2.typing?

### ISSUE THREAD

**Issue by mhluska** [skvark/opencv-python#880] opened 2023-08-03 03:15 UTC
### Expected behaviour

It sounds like opencv has Python type stubs now and people are using them in v4.x: https://github.com/opencv/opencv/issues/23782

### Actual behaviour

They don't exist

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by Avasam** [comment] 2023-08-06 16:58
Duplicate of #869, fixed by #870, not yet published.

For now you can either:
- install a development wheel from GitHub. Example: https://github.com/Toufool/AutoSplit/commit/d20cc3958d4ae5ba8ba3278926ffc2b7cc62d94d#diff-7a3ce58e9448657fa8ab45e91f4cd0ad00ddb48e18e9fdca941aa56ac1b15c2d
- or add a `cv2/typing/__init__.pyi` stub with the missing definitions into a `typing` folder in your project + wrap the import in `if TYPE_CHECKING:`

**Closed as completed** 2023-08-09 11:34 UTC
Labels: duplicate

**Comment by mhluska** [comment] 2023-08-17 01:13
Is this actually fixed? I am using the latest version 4.8.0.76 but still seeing an error:

```
Name "cv2.typing.MatLike" is not defined
```
