### ISSUE TITLE
CoreImage.framework not found

### ISSUE THREAD

**Issue by cbenhagen** [skvark/opencv-python#73] opened 2018-03-02 10:42 UTC
### Steps to reproduce

```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2/cv2.so, 2): Library not loaded: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2/.dylibs/libavcodec.57.107.100.dylib
  Reason: image not found
```

- operating system
macOS 10.10.5

- architecture (e.g. x86)
x86_64

- opencv-python version
3.3.1.11, 3.4.0.12

- latest working opencv-python version
3.3.0.10

See also:
https://stackoverflow.com/questions/47963386/image-not-found-error-after-installing-opencv-python-wheel-on-mac

**Comment by skvark** [comment] 2018-03-02 11:34
Most likely a duplicate of #67 & #72. The issue has been fixed in the latest development builds but there are some other issues on Linux side which are still blocking a new release.

**Closed by skvark** 2018-03-02 11:34 UTC
