### ISSUE TITLE
Cannot use sift and other nonfree modules

### ISSUE THREAD

**Issue by simbaforrest** [skvark/opencv-python#132] opened 2018-10-17 13:24 UTC
### Expected behaviour

I was using opencv-contrib-python. I was hoping I can use:

> sift = cv2.xfeatures2d_SURF.create()
    kp = sift.detect(gray, None)

### Actual behaviour

But when I run sift, there is the following error:

> cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv_contrib\modules\xfeatures2d\src\surf.cpp:1016: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'cv::xfeatures2d::SURF::create'

### Steps to reproduce

- example code
```python   
import numpy as np
import cv2

gray = np.zeros((480,640), np.uint8)

sift = cv2.xfeatures2d_SURF.create()
kp = sift.detect(gray, None)

img = cv2.drawKeypoints(gray, kp)

cv2.imwrite('sift.jpg', img)
```
- operating system: Win 10
- architecture: x64
- opencv-python version: 3.4.3

**Comment by waveform80** [comment] 2018-10-17 13:30
Duplicate of #126

**Closed** 2018-10-17 13:37 UTC
