### ISSUE TITLE
cv2.imshow() not working consistently

### ISSUE THREAD

**Issue by GokulNarayan** [skvark/opencv-python#362] opened 2020-07-16 16:30 UTC
### Expected behaviour

imshow displays image

### Actual behaviour

when calling cv2.imshow(), I mostly get a small window with the correct name but containing only a black screen. It does work sometimes however but it is unpredictable. This issue was not encountered in previous versions of opencv-contrib-python.
![error](https://user-images.githubusercontent.com/43655410/87697368-9e4ab600-c757-11ea-98b9-d88afcdc83d5.png)

### Steps to reproduce

- example code

import cv2
import os
import imutils

image = cv2.imread("ref_image.png")

cv2.imshow("test", image)
cv2.waitKey(0)

cv2.destroyAllWindows() 

- operating system : Ubuntu 20.04
- architecture (e.g. x86): x64
- python version: 3.8
- opencv-python version: opencv-contrib-python 4.3.36

**Comment by skvark** [comment] 2020-07-16 21:17
Yeah, probably same issue as here: https://github.com/skvark/opencv-python/issues/356

I have no idea what causes the behavior. Qt4 version is the same, only the base image where the wheels and Qt4 are built was changed from ``manylinux1`` to ``manylinux2014``.

**Comment by rockbass2560** [comment] 2020-07-18 03:18
@skvark Do you know any workaround to solve this? it happens on any version of opencv-contrib-python using ubuntu 20

**Comment by skvark** [comment] 2020-07-18 11:53
I had a look at the linked OpenCV issue and it seems that this issue is related to Qt conflicts. There is no workaround, best option would be to bundle Qt5 to the wheels (Qt4 is very old and does not behave well with other global Qt system installations) but there were major issues when I tried that during the manylinux version upgrade. Auditwheel might as well cause the issue, it bundles the dependencies into the wheels and it might be doing something wrong.

**Comment by skvark** [comment] 2020-07-18 12:07
How to avoid this issue until it's solved:

- downgrade to the previous release which uses ``manylinux1`` (4.2.0 and 3.4.9)
- use some proper GUI framework to display the images such as PyQt5
- build OpenCV wheel locally and use it, instructions are in the readme: https://github.com/skvark/opencv-python#manual-builds

**Comment by skvark** [comment] 2020-07-20 12:49
I will rebuild the ``manylinux2014`` images and check if that fixes this issue, auditwheel has had some updates since the last build.

**Comment by skvark** [comment] 2020-07-21 15:50
That didn't help, I'll need to probably start looking into Qt5 again...

**Comment by skvark** [comment] 2020-07-29 20:22
Looks like I got the Qt5 builds working (at least Travis tests are passing), but I need to still check that GUI functions actually work.

**Comment by skvark** [comment] 2020-08-06 19:05
I patched ``auditwheel`` and got Qt 5.15 working. Qt is also built in a namespace so it should not conflict with other systems Qt installations in the future. There is still some font related finetuning to do but it's far more easier to fix than the segmentation fault issue.

**Comment by skvark** [comment] 2020-08-09 15:01
This issue should be now fixed. Fixed wheels (3.4.10.37 and 4.3.0.38) will be soon up in PyPI. It will take probably about ~24 hours for all builds to finish.

Please open a new issue if there are still problems related to GUI functions.

**Closed by skvark** 2020-08-09 15:01 UTC

**Comment by ParthikB** [comment] 2020-08-12 19:03
What's the solution finally?

**Comment by skvark** [comment] 2020-08-12 19:11
Solution to this issue? Upgrade your ``opencv-python`` to version 4.3.0.38 or greater.

**Comment by SiddhantKumar14** [comment] 2020-09-15 05:46
upgrading to 4.3.0.38 did not work, still facing the same issue

**Comment by skvark** [comment] 2020-09-15 05:58
Please post exact install steps and how you are using `opencv-python` and please upgrade to 4.4.0. This issue has been fixed, the issue is very likely in your environment.

**Comment by SiddhantKumar14** [comment] 2020-09-15 06:05
upgrading to 4.4.0 fixed it, thank you!

**Comment by muhammad2k18** [comment] 2020-10-06 07:23
I am using the latest conda version for Debian on parrot OS security(updated to latest version)
I'm running my script in a venv with python3.7, qt5.9, OpenCV-python4.4.0.44
![Screenshot spider cv output at 2020-10-03 13-12-00](https://user-images.githubusercontent.com/36593756/95170957-ba815080-07a4-11eb-9d33-794953027c94.png)
with this: QObject::moveToThread: Current thread (0x55e37f4716b0) is not the object's thread (0x55e37f6733f0).
Cannot move to target thread (0x55e37f4716b0)

**Comment by ganler** [comment] 2020-11-15 11:21
OpenCV 4.4 worked to show the image. But the warning is still there.

**Comment by ikram-hamizi** [comment] 2021-04-25 04:05
> I am using the latest conda version for Debian on parrot OS security(updated to latest version)
> I'm running my script in a venv with python3.7, qt5.9, OpenCV-python4.4.0.44
> ![Screenshot spider cv output at 2020-10-03 13-12-00](https://user-images.githubusercontent.com/36593756/95170957-ba815080-07a4-11eb-9d33-794953027c94.png)
> with this: QObject::moveToThread: Current thread (0x55e37f4716b0) is not the object's thread (0x55e37f6733f0).
> Cannot move to target thread (0x55e37f4716b0)

@ahmad-sulehari Upgrading to 38+ resulted in the same issue as you.
To solve the ` QObject::moveToThread:` problem, only opencv==4.3.0.36 worked for me (following the comment here: #https://github.com/Yuliang-Liu/Curve-Text-Detector/issues/11#issuecomment-762640216)

**Comment by matanster** [comment] 2021-05-24 09:37
With 4.3.0.36, and only that version, I no longer get the original warning, but multiple windows open up when reusing `imshow()`, which was not the case before. Installing 4.4.0.42 reverts back to the original problem of showing that warning message. So still exploring ... 

(One thing I do notice is that it's easy to end up with an _opencv-contrib-python_ package that is not the same version as _opencv-python_ itself, which may add to some people's confusion in fiddling version installs).

**Comment by matanster** [comment] 2021-05-24 10:08
Thanks a lot. Would you happen to recall how to build OpenCV from source in a way that gets picked up within a conda environment?

**Comment by skvark** [comment] 2021-05-24 10:28
I don't know about conda, these packages are for PyPI and `pip`. If you use `pip`, follow the manual build instructions in the README. Conda has also their own OpenCV packages here: https://github.com/conda-forge/opencv-feedstock

**Comment by matanster** [comment] 2021-05-25 07:06
In case it ever helps anyone for that qt compatibility situation, here's how to manage [building from source for a conda environment](https://stackoverflow.com/a/67677739/1509695), which I didn't see documented anywhere else.

**Comment by pk16514** [comment] 2021-07-29 16:35
Use pip install opencv-python==4.2.0.34 . It worked for me. No warning and working consistently without any black image.

**Comment by leosongwei** [comment] 2021-09-02 10:41
got the same problem on 4.5.3.56, OS is Debian 11

**Comment by camilocamachour** [comment] 2021-10-29 23:12
Same problem with 4.5.3.56 on Ubuntu 18.04 and Python 3.8.

**Comment by vocdex** [comment] 2022-04-21 08:07
Using the latest OpenCV at them moment(4.5.5.64), but this behaviour is still happening. Any suggestions?

**Comment by angeliquemccl** [comment] 2022-07-14 20:07
If it everything is update per the previous comments. I found out it could be the image size, try using:

def rescaleFram(frame, scale=0.75):

14.23 seconds in the video 

https://www.youtube.com/watch?v=oXlwWbU8l2o

**Comment by apolloo43** [comment] 2024-03-24 10:38
it same as me..  i using python 3.8 , ubuntu 20.04 and opencv version 4.8.0.76 and same problem happen.. are there any solution???
