### ISSUE TITLE
help

### ISSUE THREAD

**Issue by redparck** [skvark/opencv-python#272] opened 2019-12-21 08:09 UTC
Hello, developer

I was recently doing a small experiment with Jeston nano, one of which relies on OpenCV python. But at present, there are only x86 platforms. If you can provide the installation package based on aarch64, it will be a great help to me. Thank you

**Comment by skvark** [comment] 2019-12-21 19:43
Duplicate of https://github.com/skvark/opencv-python/issues/13

**Closed by skvark** 2019-12-21 19:43 UTC
