### ISSUE TITLE
OpenCV with Python wont exit properly when using detectMultiScale on CascadeClassifier

### ISSUE THREAD

**Issue by handersendk** [skvark/opencv-python#339] opened 2020-06-06 06:22 UTC
### Expected behaviour
When using detectMultiScale I expect python to do a clean exit. 

`faces = FACE_CLASSIFIER.detectMultiScale(gray, scaleFactor=SCALE_FACTOR, minNeighbors=MIN_NEIGHBORS)`

### Actual behaviour
Python is unable to do a clean exits and crashes. The method still works however but the application wont do a clean exit. 

I discovered that the problem is related to specific opencv-contrib-python packgages. 

These versions fail to run the application with clean exit.
```
pip3 install opencv-contrib-python==3.4.9.31
pip3 install opencv-contrib-python==3.4.9.33
pip3 install opencv-contrib-python==4.2.0.32
```

I have tested the following packages and they all work.
```
pip3 install opencv-contrib-python==3.4.2.16
pip3 install opencv-contrib-python==3.4.2.17
pip3 install opencv-contrib-python==3.4.3.18
```

These versions all introduce this warning but it still works.
[ WARN:1] terminating async callback
```
pip3 install opencv-contrib-python==3.4.4.19
pip3 install opencv-contrib-python==3.4.5.20
pip3 install opencv-contrib-python==3.4.6.27
pip3 install opencv-contrib-python==3.4.7.28
pip3 install opencv-contrib-python==3.4.8.29
pip3 install opencv-contrib-python==4.0.0.21
pip3 install opencv-contrib-python==4.0.1.23
pip3 install opencv-contrib-python==4.0.1.24
pip3 install opencv-contrib-python==4.1.0.25
```

These version all introduce this warning but it still works.
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

```
pip3 install opencv-contrib-python==4.1.1.26
pip3 install opencv-contrib-python==4.1.2.30
```

### Steps to reproduce
Sample code

I start with from commandline using
`python face.py
`
face.py

```
import cv2

FACE_CLASSIFIER = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
SCALE_FACTOR = 1.5
MIN_NEIGHBORS = 5

video_capture = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # If this line is removed the program exits properly 
    faces = FACE_CLASSIFIER.detectMultiScale(gray, scaleFactor=SCALE_FACTOR, minNeighbors=MIN_NEIGHBORS)

    cv2.imshow('Video', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

```
System information

```
Microsoft Windows [Version 10.0.18363.836]

pip3 list
Package               Version
--------------------- --------
numpy                 1.18.5
opencv-contrib-python 3.4.9.33
pip                   20.1.1
setuptools            41.2.0

python --version
Python 3.7.7
```

More details can be found here. 
[https://stackoverflow.com/questions/62211684/opencv-with-python-wont-exit-properly-when-using-detectmultiscale-on-cascadeclas](https://stackoverflow.com/questions/62211684/opencv-with-python-wont-exit-properly-when-using-detectmultiscale-on-cascadeclas
)

**Comment by skvark** [comment] 2020-06-06 18:55
Duplicate of https://github.com/skvark/opencv-python/issues/198

**Closed by skvark** 2020-06-06 18:55 UTC

**Comment by skvark** [comment] 2020-06-06 19:26
About the crash which is maybe a new issue related to those method, open a new issue to the OpenCV repository. I cannot fix OpenCV bugs here, this repository contains only a automated toolchain which compiles OpenCV releases and pushes them to PyPI.

**Comment by handersendk** [comment] 2020-06-07 18:43
I tried to open a bug at opencv here 

[https://github.com/opencv/opencv/issues/17495](https://github.com/opencv/opencv/issues/17495)



>     pip
>     opencv-contrib-python
>     opencv-python
> 
> These packages are not supported here (they are unofficial).
> 
> So, please minimize dependencies and build from sources (with debug symbols) and capture stacktraces.

But they state the packages are not supported there. I am now not sure as to where to report this bug then?

**Comment by skvark** [comment] 2020-06-07 18:51
Well, you should do as they say. If you can replicate with a manually built OpenCV, then the issue is in OpenCV. If not, then the issue is in the Appveoyr build environment / configuration used in the packages provided by this repository. However, in my experience it is highly unlikely since there hasn't been any changes in the build process between those working and non-working releases.

**Comment by handersendk** [comment] 2020-06-07 18:59
Ok. I am not familiar with manually building opencv. If I choose to do so would I be able to run my python code or would it require me to rewrite it to c/c++ (not sure as to what opencv uses natively)?

**Comment by skvark** [comment] 2020-06-07 19:28
Yes, you can run the Python code given that you choose to generate the Python compatible OpenCV binary in the build configuration. OpenCV docs and countless of tutorials around the internet will provide guidance on how to do that.

Actully that's what this repository is doing. It just takes the code from the OpenCV repository, configures Cmake (the build tool) to generate the Python compatible binary (``cv2.pyd``), copies the binary to the Python package and uploads the package to PyPI. There is no Python code in the generated package expect for the couple of lines of import related logic (https://github.com/skvark/opencv-python/blob/master/cv2/__init__.py). 

Many Python packages such as ``numpy``, ``scipy`` etc. are also mostly some C / C++ / Fortran code and work the same way as OpenCV. The only difference is that OpenCV maintainers and developers do not provide any official pre-built Python packages so quite many people and organizations rely on these packages provided by me. I do this mostly alone so there's a very low treshold to close issues which do not seem to be related to the packaging code in this repository.

**Comment by handersendk** [comment] 2020-06-07 19:33
I am currently looking into as to how to build from sources. I found a guide here [https://docs.opencv.org/master/d5/de5/tutorial_py_setup_in_windows.html](https://docs.opencv.org/master/d5/de5/tutorial_py_setup_in_windows.html)

Thank you for taking time to reply and maintaining the opencv-python :) I will update issue at opencv repo if I manage to make it fail with stacktraces.

**Comment by beelabcloud** [comment] 2022-06-07 09:24
It might be caused by the opencl. Rebuild from source without opencl works for me.

**Comment by alalek** [comment] 2022-06-07 10:17
`OPENCV_OPENCL_RUNTIME=disabled` environment variable may help without rebuild: https://github.com/opencv/opencv/wiki/OpenCL-optimizations

**Comment by HOLLYwyh** [comment] 2024-03-24 14:05
`pip install opencv-python==4.9.0.80`  works for me.
